query getPage($id: uuid!, $include_user: Boolean!, $user_id: uuid!) {
  page: pages_by_pk(id: $id) {
    id
    name
    description
    profile_image
    cover_image
    avatar_color
    status
    created_by
    created_at
    updated_at
    language_code
    page_categories {
      category_id
      category {
        id
        name
      }
    }
    page_admins {
      id
      user_id
      role

      user {
        id
        full_name
        user_name
        profile_image
        avatar_color
      }
    }
    page_followers(where: { user_id: { _eq: $user_id } }, limit: 1)
      @include(if: $include_user) {
      id
    }
    followers_count
  }
}
