query getBookmarkedPrayerRequests(
  $filter: bookmarked_prayers_bool_exp
  $order: [bookmarked_prayers_order_by]
  $limit: Int
  $offset: Int
) {
  bookmarked_prayers(
    where: $filter
    order_by: $order
    limit: $limit
    offset: $offset
  ) {
    id
    prayer_request_id
  }
}
