query getPrayerListItems(
  $filter: prayer_list_items_bool_exp
  $order: [prayer_list_items_order_by]
  $limit: Int
  $offset: Int
  $user_id: uuid!
  $include_user: Boolean!
) {
  prayer_list_items(
    where: $filter
    order_by: $order
    limit: $limit
    offset: $offset
  ) {
    id
    prayer_list_id
    created_at
    scheduled_date
    scheduled_week
    prayer_request {
      id
      title
      description
      created_at
      status
      for_who
      photo_url

      # ------------------------------Prayed by user ------------------------------
      prayer_prayeds(where: { user_id: { _eq: $user_id } }, limit: 1)
        @include(if: $include_user) {
        id
      }

      feed {
        id
        user {
          id
          full_name
          profile_image
          avatar_color
        }
        group {
          id
          name
          profile_image
          avatar_color
        }
        page {
          id
          name
          profile_image
          avatar_color
        }
        comment_count
        reaction_count
        share_count
        feed_reactions {
          id
          reaction_type
          user_id
        }
      }
    }
  }

  prayer_list_items_aggregate(where: $filter) {
    aggregate {
      count
    }
  }
}
