query getPrayerPrayed(
  $filter: prayer_prayed_bool_exp
  $order: [prayer_prayed_order_by]
  $limit: Int
  $offset: Int
) {
  prayer_prayed(
    where: $filter
    order_by: $order
    limit: $limit
    offset: $offset
  ) {
    id
    prayer_request_id
  }
}
