query getUserPrayerLists(
  $user_id: uuid!
  $limit: Int
  $offset: Int
  $order: [prayer_list_order_by]
  $filter: prayer_list_bool_exp_bool_exp
) {
  user_prayer_lists(
    args: { user_id: $user_id }
    limit: $limit
    offset: $offset
    order_by: $order
    where: $filter
  ) {
    id
    name
    type
    group_id
    scheduled_date
    scheduled_week
    num_requests
    num_prayed
    percentage_completed
  }
}
