query getLotteryTickets(
  $filter: tickets_bool_exp
  $order: [tickets_order_by]
  $limit: Int
  $offset: Int
  $user_id: uuid
) {
  tickets(where: $filter, order_by: $order, limit: $limit, offset: $offset) {
    id
    lottery_id
    name
    phone_number
    ticket_number
    status
    created_at
    receipt_url
    created_by
    user_id
    user {
      id
      phone
      id
      name
      profile_image
      avatar_color
    }
    lottery {
      id
      lottery_id
      total_tickets
      price_per_ticket
      created_at
      status
      description
      when_all_tickets_sold
      total_sold_tickets

      likes(where: { user_id: { _eq: $user_id } }) {
        id
        user_id
      }

      user {
        id
        name
        phone
        profile_image
        number_of_lotteries
        phone
        alternate_phone
        total_likes
        rating
      }

      end_date
      items(order_by: { order: asc }) {
        id
        title
        order
        category_id
        category {
          id
          name
          icon
        }

        winner {
          ticket_id
          ticket {
            id
            lottery_id
            name
            phone_number
            ticket_number
            status
            created_at
            receipt_url
            created_by
            user_id
            user {
              phone
              id
              name
              profile_image
              avatar_color
            }
          }
        }
      }
      medias {
        id
        url
        is_featured
      }
    }
  }

  tickets_aggregate(where: $filter) {
    aggregate {
      count
    }
  }
}
