query getLanguages(
  $filter: languages_bool_exp
  $order: [languages_order_by]
  $limit: Int
  $offset: Int
) {
  languages(where: $filter, order_by: $order, limit: $limit, offset: $offset) {
    name
    code
    native_name
    rtl
  }
}
