query getDevotionItem($id: uuid!, $include_user: Boolean!, $user_id: uuid!) {
  devotion_devotions_by_pk(id: $id) {
    id
    title
    content
    created_at
    updated_at
    cover_image

    series_id

    read_count
    # User reads
    reads(where: { user_id: { _eq: $user_id } }, limit: 1)
      @include(if: $include_user) {
      id
      user_id
      read_at
    }

    series {
      id
      title
      cover_image
      created_at
      updated_at

      devotions_aggregate {
        aggregate {
          count
        }
      }
    }
    feed {
      id
      type
      created_at
      created_by
      visibility
      comment_count
      reaction_count
      share_count
      page {
        id
        name
        description
        profile_image
        avatar_color
        cover_image

        page_followers(where: { user_id: { _eq: $user_id } }, limit: 1)
          @include(if: $include_user) {
          id
        }

        page_admins(where: { user_id: { _eq: $user_id } }, limit: 1)
          @include(if: $include_user) {
          id
          role
          user_id
        }
      }
      group {
        id
        name
        description
        cover_image
        created_at
        updated_at
        avatar_color
        profile_image
        group_members(where: { user_id: { _eq: $user_id } }, limit: 1)
          @include(if: $include_user) {
          id
          role
          status
          user_id
        }
      }
    }
    created_by
    user {
      id
      full_name
      profile_image
      avatar_color
    }

    # computed
    comment_count
    reaction_count
    feed {
      feed_reactions(where: { user_id: { _eq: $user_id } })
        @include(if: $include_user) {
        id
        reaction_type
        feed_id
        user_id
      }
    }
  }
}
