query getDevotions(
  $filter: devotion_devotions_bool_exp
  $order: [devotion_devotions_order_by]
  $limit: Int
  $offset: Int
  $include_user: Boolean!
  $user_id: uuid!
) {
  devotion_devotions(
    where: $filter
    order_by: $order
    limit: $limit
    offset: $offset
  ) {
    id
    title
    content
    created_at
    updated_at
    cover_image
    visibility
    series_id

    read_count
    # User reads
    reads(where: { user_id: { _eq: $user_id } }, limit: 1)
      @include(if: $include_user) {
      id
      user_id
      read_at
    }

    feed {
      id
      type
      created_at
      created_by
      visibility
      comment_count
      reaction_count
      share_count
      feed_reactions(where: { user_id: { _eq: $user_id } }, limit: 1)
        @include(if: $include_user) {
        id
        reaction_type
        user_id
        feed_id
      }
      user {
        id
        full_name
        profile_image
        avatar_color
      }

      page {
        id
        name
        description
        profile_image
        avatar_color

        page_followers(where: { user_id: { _eq: $user_id } }, limit: 1)
          @include(if: $include_user) {
          id
        }

        page_admins(where: { user_id: { _eq: $user_id } }, limit: 1)
          @include(if: $include_user) {
          id
          role
        }
      }
      group {
        id
        name
        description
        cover_image
        created_at
        updated_at
        avatar_color
        group_members(where: { user_id: { _eq: $user_id } }, limit: 1)
          @include(if: $include_user) {
          id
          role
          status
        }
      }
    }
    series {
      id
      title
      cover_image
      created_at
      updated_at
      visibility
      devotions_aggregate {
        aggregate {
          count
        }
      }

      created_by
      user {
        id
        full_name
        profile_image
        avatar_color
      }
    }
  }

  devotion_devotions_aggregate(where: $filter) {
    aggregate {
      count
    }
  }
}
