mutation updateDevotionSeries($input: devotion_series_set_input!, $id: uuid!) {
  update_devotion_series_by_pk(pk_columns: { id: $id }, _set: $input) {
    id
    title
    description
    cover_image
    visibility
    updated_at
  }
}
