query getEventCategories(
  $filter: event_categories_bool_exp
  $order: [event_categories_order_by]
  $limit: Int
  $offset: Int
) {
  event_categories(
    where: $filter
    order_by: $order
    limit: $limit
    offset: $offset
  ) {
    id
    name
    icon
    slug
    description
    is_active
  }
}
