mutation addComment($input: comments_insert_input!) {
  insert_comments_one(object: $input) {
    id
    content
    created_at
    feed_id
    parent_comment_id
    user {
      id
      full_name
      profile_image
    }
  }
}
