query getReportTypes(
  $filter: report_types_bool_exp
  $order: [report_types_order_by]
  $limit: Int
  $offset: Int
) {
  report_types(
    where: $filter
    order_by: $order
    limit: $limit
    offset: $offset
  ) {
    id
    code
    label
  }
  report_types_aggregate(where: $filter) {
    aggregate {
      count
    }
  }
}
