mutation miniAppLogin($initData: String!) {
  mini_app_login(arg1: { init_data: $initData }) {
    refresh_token
    token
    user {
      id
      name
      phone
      alternate_phone
      role
      is_phone_verified
      profile_image
      avatar_color
      telegram_user_id
    }
  }
}
