mutation createGroup($input: prayer_groups_insert_input!) {
  insert_prayer_groups_one(object: $input) {
    id
    name
    description
    cover_image
    allow_guests_to_view
    cover_image
    created_at
    auto_approve_members
    id
    is_private
    invite_only
    owner_id
  }
}
