query getGroupMembers(
  $filter: group_members_bool_exp
  $order: [group_members_order_by]
  $limit: Int
  $offset: Int
) {
  group_members(
    where: $filter
    order_by: $order
    limit: $limit
    offset: $offset
  ) {
    id
    user {
      id
      full_name
      user_name
      profile_image
      avatar_color
    }
    role
    status
    joined_at
    group_id
    user_id

    group: prayer_group {
      id
      name
      description
      cover_image
      profile_image
      created_at
      is_private
      allow_guests_to_view
      invite_only
      auto_approve_members
      allow_members_to_invite_other
      allow_members_to_share_prayer

      allow_members_to_create_request
      allow_members_to_create_devotion
      allow_members_to_create_testimony
      id
      status
      owner_id
      avatar_color
    }
  }
  group_members_aggregate(where: $filter) {
    aggregate {
      count
    }
  }

  # For approved members
  group_members_aggregate(where: $filter) {
    aggregate {
      count
    }
  }
}
