query getGroups(
  $filter: prayer_groups_bool_exp
  $order: [prayer_groups_order_by!]
  $limit: Int
  $offset: Int
) {
  prayer_groups(
    where: $filter
    order_by: $order
    limit: $limit
    offset: $offset
  ) {
    id
    name
    description
    cover_image
    allow_guests_to_view
    profile_image
    created_at
    auto_approve_members
    id
    is_private
    invite_only
    owner_id
    avatar_color
    group_members {
      id
      invited_by
      joined_at
      role
      status
      user {
        id
        full_name
        profile_image
      }
    }
  }

  prayer_groups_aggregate(where: $filter) {
    aggregate {
      count
    }
  }
}
