mutation updateGroup(
  $input: prayer_groups_set_input!
  $id: uuid!
  $category_input: [group_categories_insert_input!]!
) {
  # remove group categories
  delete_group_categories(where: { group_id: { _eq: $id } }) {
    affected_rows
  }

  # add group categories (only if category_input is provided)
  insert_group_categories(objects: $category_input) {
    affected_rows
  }

  update_prayer_groups_by_pk(_set: $input, pk_columns: { id: $id }) {
    id
  }
}
