mutation addUserPaymentOption($input: user_payment_options_insert_input!) {
  insert_user_payment_options_one(object: $input) {
    id
    user_id
    payment_option_id
    account_number
    account_name
    payment_option {
      id
      name
    }
  }
}
