query getUserPaymentOptions(
  $filter: user_payment_options_bool_exp
  $order_by: [user_payment_options_order_by]
  $limit: Int
  $offset: Int
) {
  user_payment_options(
    where: $filter
    order_by: $order_by
    limit: $limit
    offset: $offset
  ) {
    id
    user_id
    payment_option_id
    account_number
    account_name
    payment_option {
      id
      name
    }
  }

  total: user_payment_options_aggregate(where: $filter) {
    aggregate {
      count
    }
  }
}
