query getNotifications(
  $filter: user_notifications_bool_exp
  $order: [user_notifications_order_by]
  $limit: Int
  $offset: Int
) {
  user_notifications(
    where: $filter
    order_by: $order
    limit: $limit
    offset: $offset
  ) {
    id
    user_id
    notification {
      id
      title
      content
      created_at
      type
      payload
    }
  }
  user_notifications_aggregate(where: $filter) {
    aggregate {
      count
    }
  }
}
